Carotene Strings
Hachimi-Hachimi/tl-en pull request #5
Opened 2024-09-12 17:25 UTC by KevinVG207

2024-09-13 13:59 UTC, LeadRDRK requested changes

2024-09-13 13:59 UTC, LeadRDRK commented on localized_data/localize_dict.json
> +    "StoryEvent0041": "Time left: $(plural {0} '$ day' '$ days')",
This is rather opinionated, but could you replace all occurrences of "Time left:" with "Event ends in" (for events) or "Ends in" (for other contexts)? Hachimi's TLs have been using this convention for a while and I just think it looks nicer.

2024-09-13 13:59 UTC, LeadRDRK commented on localized_data/localize_dict.json
> +    "SingleMode0045": "$(nb)$(ho 1)Are you sure you want to buy \nthe above skills?",
Shouldn't it be "learn" instead of "buy"? I have no idea what the original word said but I think it makes more sense.

2024-09-13 13:59 UTC, LeadRDRK commented on localized_data/localize_dict.json
> +    "SingleMode0214": "Buy Skill(s)",
Shouldn't it be "learn" instead of "buy"?

2024-09-13 14:28 UTC, KevinVG207 commented
Will make the requested changes when I can. If you find anything else that you want me to revert to keep consistency for current users, let me know.

2024-09-13 17:49 UTC, KevinVG207 commented on localized_data/localize_dict.json
> +    "StoryEvent0041": "Time left: $(plural {0} '$ day' '$ days')",
Will do.

2024-09-13 17:51 UTC, KevinVG207 commented on localized_data/localize_dict.json
> +    "SingleMode0045": "$(nb)$(ho 1)Are you sure you want to buy \nthe above skills?",
JP would be something like "acquire" but learn sounds better. I probably did this for space constraints on a different string? Will have to check this one after changing.

2024-09-13 17:51 UTC, KevinVG207 commented on localized_data/localize_dict.json
> +    "SingleMode0214": "Buy Skill(s)",
See other message about this.

2024-09-14 01:44 UTC, LeadRDRK commented on localized_data/localize_dict.json
> +    "SingleMode0045": "$(nb)$(ho 1)Are you sure you want to buy \nthe above skills?",
This string was previously already merged into tl-en. I did exactly what I described and it worked just fine in my testing.

2024-09-15 10:38 UTC, LeadRDRK approved these changes

2024-09-15 10:42 UTC, merged