Carotene Assets
Hachimi-Hachimi/tl-en pull request #6
Opened 2024-09-12 17:38 UTC by KevinVG207

2024-09-13 14:39 UTC, LeadRDRK requested changes
These changes should be taken before merging or they will be made after this is merged. Decisions are not final; please reply to each of these comments, let me know your opinion and maybe make these changes yourself.

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/an_texture_sets/as_uMeshParam_fl_singlemode_icon_motivation00/tx_uTex_fl_singlemode_icon_motivation00_0.diff.png
Replace "Normal" motivation icon with Rekoiru's sprite

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/textures/uianimation/flash/singlemode/statusicon/utx_ico_motivation_l_02.diff.png
Replace "Normal" motivation icon with Rekoiru's sprite

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/an_texture_sets/as_uMeshParam_fl_footer_btn00/tx_uTex_fl_footer_btn00_0.diff.png
Keep tl-en's texture

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/atlas/common/common.diff.png
Replace strategy icons with Rekoiru's sprites

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/uianimation/flash/singlemode/arc/pf_fl_singlemode_arc_header_turncounter00.json
Keep tl-en's file

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/uianimation/flash/singlemode/cook/pf_fl_singlemode_cook_header_turncounter00.json
Keep tl-en's file

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/uianimation/flash/singlemode/free/pf_fl_singlemode_free_header_turncounter00.json
Keep tl-en's file

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/uianimation/flash/singlemode/live/pf_fl_singlemode_live_header_turncounter00.json
Keep tl-en's file

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/uianimation/flash/singlemode/pf_fl_singlemode_header_turncounter00.json
Keep tl-en's file

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/uianimation/flash/singlemode/sport/pf_fl_singlemode_sport_header_turncounter00.json
Keep tl-en's file

2024-09-13 14:39 UTC, LeadRDRK commented on localized_data/assets/uianimation/flash/singlemode/teamrace/pf_fl_singlemode_teamrace_header_turncounter00.json
Keep tl-en's file

2024-09-13 15:19 UTC, KevinVG207 commented
I hadn't seen #4 before now and Rekoiru seems to have done a great number of UI textures. Would it not be better to make few changes to their textures rather than mine?
Examples: Change Horsegirl to Umamusume in their home.png and change Awful to Worst for their motivation sprites. (Thinking about this made me realize I need to change wis to wit in common.png).

I'm not quite sure what your plan is atm. Perhaps to accept mine first and adjust+add theirs later?

2024-09-13 15:29 UTC, LeadRDRK commented
#4 couldn't be merged as-is due to the use of complete textures prior to the introduction of the texture diffing feature. I'm planning to merge yours first and then add or modify textures with those from Reko's PR. Some of the changes I requested didn't involve Reko's PR tho, so you could do those first for me.

2024-09-14 07:54 UTC, KevinVG207 commented on localized_data/assets/atlas/common/common.diff.png
For strategy icons, I prefer mine because the arrow-style indicators may help new players know which direction the race direction is (and thus what is front and what is back). Also I based them off strategy icons the game already uses.

2024-09-14 08:18 UTC, KevinVG207 commented on localized_data/assets/an_texture_sets/as_uMeshParam_fl_footer_btn00/tx_uTex_fl_footer_btn00_0.diff.png
I'm fine with this except for the "in" of the "in campaign" sprite. I find it reads strangely and it looks cramped. I think it's pretty obvious that a campaign is ongoing when that banner is present.

2024-09-14 08:32 UTC, LeadRDRK commented on localized_data/assets/atlas/common/common.diff.png
I'm merely picking Reko's icons over yours because I think they fit the overall design cues better with the rounded shapes and such, although I would agree that the arrow shape better conveys what they represent. Something about them just throws me off tho, maybe the arrows are a bit taller than what I prefer...? And which strategy icons are you referring to? I'd like to see a sample of them.

2024-09-14 08:43 UTC, LeadRDRK commented on localized_data/assets/an_texture_sets/as_uMeshParam_fl_footer_btn00/tx_uTex_fl_footer_btn00_0.diff.png
Alright, will edit my sprite to just say "Campaign".

2024-09-14 08:46 UTC, KevinVG207 commented on localized_data/assets/atlas/common/common.diff.png
![image](https://github.com/user-attachments/assets/461c3e37-303c-430b-b4d5-f1dc4eb9fef8)
These ones that are in the vanilla common.png (Rekoiru replaced these with lines as well...?)

2024-09-14 11:35 UTC, KevinVG207 commented on localized_data/assets/an_texture_sets/as_uMeshParam_fl_footer_btn00/tx_uTex_fl_footer_btn00_0.diff.png
I have removed the changes to the footer image from this branch.

2024-09-15 10:50 UTC, LeadRDRK approved these changes

2024-09-15 11:10 UTC, merged